### ISSUE TITLE
Some buttons has audio Id flag unchecked so no beeps.

### ISSUE THREAD

**Issue by thghca** [Guizz27/DWIN_LK4Pro#6]
- Filament change
- Temperature presets
- filament load/unload
- stats on about screen
- space on kyyboad gcode
- yes/no on pause,resume and power loss popups 
- all buttons bar back on avanced settings screens
- save and restore on eeprom

Also why so many almost same popups? May be better combine them in one and set text from fimware.

**Comment by Guizz27** [comment]
Thanks for the comments. I don't think I have a speaker in my screen so I didn't notice it was missing beeps.
I'm working on a screen generator that would make it easier to fix these kind of things.
Sometimes there are similar screens because it is easier to process the buttons in Marlin. I don't like the way popups are handled in Marlin. I have to check the code again but I totally agree that there should be fewer screens that are similar.
